In [1]:
import pandas as pd

data = pd.read_csv('avito_wo_nan.csv')
data = data.drop(['Unnamed: 0', 'Руль', 'Цвет', 'Объём двигателя'], axis=1)
data_new = data.drop(['VIN или номер кузова', 'Ссылка'], axis=1)

data_dummies = pd.get_dummies(data=data_new, columns=['Марка', 'Модель', 'Тип кузова',
                                                      'Привод', 'Тип двигателя',
                                                      'Состояние', 'Коробка передач'])

X = data_dummies.drop(['Цена'], axis=1).values
y = data_dummies['Цена'].values

from sklearn.preprocessing import Normalizer

transformer = Normalizer().fit(X) # fit does nothing.
transformer
Normalizer(copy=True, norm='l2')
transformer.transform(X)

array([[1.25614805e-02, 6.24949277e-06, 2.12482754e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.88006923e-02, 2.43152428e-05, 1.09418593e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.27951193e-02, 1.27377992e-05, 1.34383781e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.19753261e-02, 1.19039026e-05, 9.70168066e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.07128054e-02, 2.05892698e-05, 1.67802549e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.38100609e-02, 2.06120312e-05, 1.58712641e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [2]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
         X, y, test_size=0.2, random_state=42)

In [3]:
import sklearn.gradientboosting

ModuleNotFoundError: No module named 'sklearn.gradientboosting'

In [4]:
import xgboost

In [10]:
import numpy as np

In [19]:
%%time

eta_ = np.linspace(0.01, 0.2, 5)
subsample_ = np.linspace(0.5, 1, 5)
max_deth_ = np.linspace(3, 8, 5)



reg = xgboost.XGBRegressor(n_estimators=1000, tree_method='gpu_hist')

from sklearn.model_selection import GridSearchCV

param_grid = {"eta": eta_, "subsample": subsample_, "max_deth": max_deth_}

grid = GridSearchCV(reg, param_grid=param_grid, cv=5)
grid.fit(X_train, y_train)

CPU times: user 43min 20s, sys: 15min 19s, total: 58min 39s
Wall time: 58min 48s


In [20]:
grid.best_score_

0.9176107663680722

In [21]:
grid.best_params_

{'eta': 0.01, 'max_deth': 3.0, 'subsample': 1.0}

In [13]:
reg_best = grid.best_estimator_

In [18]:
from sklearn.metrics import mean_squared_error
print(y_test)
reg_best.predict(X_test)

[ 560000. 1200000.  530000. ... 2520000.  990000.  410000.]


array([ 701849.25, 1348219.  ,  464288.94, ..., 3099899.2 ,  917110.6 ,
        466397.9 ], dtype=float32)

In [22]:
import pandas as pd
import numpy as np

data = pd.read_csv('avito_wo_nan.csv')
data = data.drop(['Unnamed: 0', 'Руль', 'Цвет', 'Объём двигателя'], axis=1)
probeg = data['Пробег'].values
data['Супер пробег'] =np.log(1 / (probeg + 1))
data_new = data.drop(['VIN или номер кузова', 'Ссылка'], axis=1)
data_new_w = data_new.loc[data_new['Тип кузова'] != 'лимузин']
data_new_w_ = data_new_w.loc[data_new_w['Цена'] > 150000]
data_new_w = data_new_w_.loc[data_new_w['Цена'] < 5000000]
data_new_w_ = data_new_w.loc[data_new_w['Пробег'] < 300000]
data_new_w = data_new_w_.loc[data_new_w_['Состояние'] != ' битый']



data_dummies = pd.get_dummies(data=data_new_w, columns=['Марка', 'Модель', 'Тип кузова',
                                                      'Привод', 'Тип двигателя',
                                                      'Состояние', 'Коробка передач'])

X = data_dummies.drop(['Цена'], axis=1).values
y = data_dummies['Цена'].values

print(data_new_w.info())

from sklearn.preprocessing import Normalizer
from sklearn.preprocessing import StandardScaler

transformer = Normalizer().fit(X) # fit does nothing.
transformer
Normalizer(copy=True, norm='l2')
transformer.transform(X)

<class 'pandas.core.frame.DataFrame'>
Int64Index: 36706 entries, 0 to 41103
Data columns (total 13 columns):
Марка                 36706 non-null object
Модель                36706 non-null object
Год выпуска           36706 non-null int64
Тип кузова            36706 non-null object
Цена                  36706 non-null float64
Привод                36706 non-null object
Тип двигателя         36706 non-null object
Состояние             36706 non-null object
Владельцев по ПТС     36706 non-null float64
Мощность двигателя    36706 non-null float64
Пробег                36706 non-null float64
Коробка передач       36706 non-null object
Супер пробег          36706 non-null float64
dtypes: float64(5), int64(1), object(7)
memory usage: 3.9+ MB
None


array([[1.25614804e-02, 6.24949276e-06, 2.12482754e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [4.88006907e-02, 2.43152420e-05, 1.09418589e-02, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.27951192e-02, 1.27377991e-05, 1.34383781e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [1.19753260e-02, 1.19039026e-05, 9.70168063e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [2.07128053e-02, 2.05892697e-05, 1.67802548e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [1.38100609e-02, 2.06120312e-05, 1.58712640e-03, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [23]:

X_train, X_test, y_train, y_test = train_test_split(
         X, y, test_size=0.2, random_state=42)

In [24]:
reg_best = grid.best_estimator_

In [26]:
reg_best.fit(X_train, y_train)
reg_best.score(X_test, y_test)

0.9527569571490305

In [29]:
y_pred = reg_best.predict(X_test)
np.sqrt(np.mean(np.abs(y_test - y_pred)))

347.97405573431365